#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('Laravel Custom Installer', '1.0.2');
$app->add(new Artesaos\LaravelInstaller\Console\NewCommand);
$app->run();